### ISSUE TITLE
Auto Layout constraint issue

### ISSUE THREAD

**Issue by deeplearningcj** [kwkhaw/Layer-Parse-iOS-Swift-Example#11] opened 2015-09-29 00:02 UTC
I got a bug when I tested the "Layer-Parse-ios-Swift-Example". I am using xcode 7 and swift 2.

When I enter into the "ConversationViewController", it shows UI Auto Layout constraint issue as following:

---

2015-09-27 12:47:17.669 ****[4979:2415335] Unable to simultaneously satisfy constraints.

Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
"<NSLayoutConstraint:0x150dc7760 H:|-(8)-[UILabel:0x150d65700](LTR) (Names: '|':UIView:0x150a31f00 )>",
"<NSLayoutConstraint:0x150d52880 UILabel:0x150d65700.right == UIView:0x150a31f00.right - 8>",
"<NSLayoutConstraint:0x150e5a0b0 UIView:0x150a31f00.width == ATLConversationView:0x14f750d70.width>",
"<NSLayoutConstraint:0x150d4d480 'UIView-Encapsulated-Layout-Width' H:[ATLConversationView:0x14f750d70(0)]>"
)
Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x150d52880 UILabel:0x150d65700.right == UIView:0x150a31f00.right - 8>
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

---

Can you help have a look at this?

**Comment by kwkhaw** [comment] 2015-09-29 15:48
Hi @cjsnowcrying , looks like it is Atlas issue.
Someone has logged an issue in Atlas-iOS https://github.com/layerhq/Atlas-iOS/issues/970

**Comment by kwkhaw** [comment] 2015-10-27 15:02
Hi @cjsnowcrying , the issue is fixed in Atlas 1.0.13. I upgraded the project the latest Atlas version in this commit: 68c8b7f05e3564ade5383bd9455a8963668a9eb1

**Closed as completed by kwkhaw** 2015-10-27 15:02 UTC

**Comment by deeplearningcj** [comment] 2015-10-27 15:52
Thank you for the notification.
